### PR TITLE
Rawls billing v2 apis

### PR DESCRIPTION
**Pull request by dvoet**
**PR checklist**
- [x] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [x] Bump the version in `project/Settings.scala` `createVersion()`
- [x] Update `CHANGELOG.md` for those libraries
- [x] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [x] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

### CODE REVIEW

**Review by Qi77Qi — CHANGES_REQUESTED** [review]
you need to do `TRAVIS-REPLACE-ME`...altho, travis might hang before it gets to that.

I'm not familiar with rawls API...maybe someone else who's more familiar with the APIs can review as well?

**Comment by dvoet** [comment]
`TRAVIS-REPLACE-ME` was already in there

**Review by marctalbott — APPROVED** [review]

**Review by rtitle — APPROVED** [review]
LGTM

**Comment by Qi77Qi** [comment]
changelog needs to be updated as well

**Review by Qi77Qi — APPROVED** [review]

**Pull request merged**
