### PR TITLE
Restore non-Stream versions of GoogleKMS* to google1

### PR DESCRIPTION
**Pull request by helgridly**
Previously this code was moved from google1 to google2 and Stream-ified. This meant that in order to integrate minor changes to google1 into Sam, I'd have had to move Sam to use Stream everywhere, which was a lot of work. This PR returns these classes to google1.

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

### CODE REVIEW

**Comment by Qi77Qi** [comment]
this looks like straight copy of what's in google2, what's the point of this?

**Comment by helgridly** [comment]
we are currently below the threshold of passing tests that will allow us to release. i have a fix that will reduce test failure rates by around 10%, and it's blocked because i needed to upgrade google1 in sam. suddenly the classes sam was relying on had disappeared, replaced with google2 versions which use streams. it turned out to be a lot of headache to move sam to streams. this PR restores the non-stream version of the classes to google1 so i can get back on track.

**Comment by Qi77Qi** [comment]
I'm still confused..Where does KMS in google use fs2.Stream?

**Comment by helgridly** [comment]
i dunno but i found i was Streaming a LOT of stuff to make it compile

**Review by dvoet — APPROVED** [review]

**Pull request merged**
