### PR TITLE
Gd unique method name space

### PR DESCRIPTION
**Pull request by gdlex4015**
Added code to create a unique name for Method workspace to facilitate paralyzation 

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

### CODE REVIEW

**Review by jmthibault79 — CHANGES_REQUESTED** [review]
There are a lot of things here that I would like you to revert.  Please re-do this PR with minimal changes only.

**Review by gdlex4015 — COMMENTED** [review]
There is a lot here that I do not recognize as my work. 
The only thing that I have done is do 2 line change to withMethod function

**Comment by gdlex4015** [comment]
I'll revert the changes and start over

**Comment by jmthibault79** [comment]
Thanks!  👍

**Pull request closed without merging**
