### PR TITLE
remove CreateWorkbenchUserAPI:

### PR DESCRIPTION
**Pull request by Qi77Qi**
**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [x] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

### CODE REVIEW

**Comment by MatthewBemis** [comment]
you'll also need to update the versions in the documentation. see https://github.com/broadinstitute/workbench-libs/blob/develop/GETTING_STARTED.md#sharing-artifacts-with-the-world for details

**Comment by Qi77Qi** [comment]
@MatthewBemis  ah thanks! I updated readme...the changelog should still be accurate, so I didn't update that nor bump version.

**Comment by aweng98** [comment]
Also update https://github.com/broadinstitute/workbench-libs/blob/develop/model/CHANGELOG.md

**Review by dvoet — APPROVED** [review]

**Comment by Qi77Qi** [comment]
@aweng98  this class is added in https://github.com/broadinstitute/workbench-libs/pull/161 very recently. the changelog update in that PR still applies, so I didn't update that.

**Comment by MatthewBemis** [comment]
@Qi77Qi you also need to add an SBT dependency to the changelog for the model package: https://github.com/broadinstitute/workbench-libs/blob/develop/model/CHANGELOG.md

This was in the instructions I linked and is also what @aweng98 is referring to

**Review by MatthewBemis — APPROVED** [review]

**Pull request merged**
