### PR TITLE
Resume publishing artifacts for both Scala 2.11 and 2.12

### PR DESCRIPTION
**Pull request by jmthibault79**
**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

After merging, _even if you haven't bumped the version_: 
- [ ] Update `README.md` and the `CHANGELOG.md` for any libs you changed with the new dependency string. The git hash is the same short version you see in GitHub (i.e. seven characters). You can commit these changes straight to develop.

### CODE REVIEW

**Comment by rtitle** [comment]
Travis is sad.. looks like maybe a variable wasn't substituted?
```
The command "SBT_OPTS=++$TRAVIS_SCALA_VERSION -Xmx3g sbt clean coverage test coverageReport -Denv.type=test && SBT_OPTS=++$TRAVIS_SCALA_VERSION -Xmx3g sbt coverageAggregate" exited with 127.
```

**Comment by jmthibault79** [comment]
Yeah I messed up some ordering

**Comment by helgridly** [comment]
Is this due to a Travis change? IIRC Travis should run all the commands once for every version listed under `scala`. Curious as to what happened here (though if it's broken and this makes it work, merge it!).

**Comment by helgridly** [comment]
See https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix for far too much detail.

**Comment by jmthibault79** [comment]
@helgridly It seems so, but I haven't identified the Travis change.  We are setting `SBT_OPTS` explicitly which may be what is negating the version setting.

**Review by rtitle — APPROVED** [review]
LGTM

**Pull request merged**
