### PR TITLE
AJ-1083: Add getHybridConnectionKey to AzureRelayService

### PR DESCRIPTION
**Pull request by rtitle**
This will be used in Leo for upgrading Relay Listener deployments. 

No version bump since it's a purely additive change.

Tested in a BEE.

**PR checklist**
- [x] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [x] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

### CODE REVIEW

**Review by Qi77Qi — APPROVED** [review]
lgtm...is this mostly just moving what's in Leo to wb-libs?

**Comment by Qi77Qi** [comment]
oh, nvm it's already in wb-libs...I was thinking of [this](https://github.com/broadinstitute/workbench-libs/blob/develop/azure/src/main/scala/org/broadinstitute/dsde/workbench/azure/AzureRelayInterp.scala#L65-L79)

**Comment by rtitle** [comment]
Yeah it was already in wb-libs, just adding a new method. Thanks 👍

**Review by LizBaldo — APPROVED** [review]
lgtm, will this be used for azure runtimes as well? I guess I will find out when reviewing the leo PR next :)

**Comment by rtitle** [comment]
> lgtm, will this be used for azure runtimes as well? I guess I will find out when reviewing the leo PR next :)

Currently this method is just used for app upgrades. We don't really have a use case for runtimes (there is no method currently to "update" images deployed on a VM).

**Pull request merged**
