### PR TITLE
QA-1759

### PR DESCRIPTION
**Pull request by gpolumbo-broad**
- Removed deprecated `BillingFixtures.withBillingProject`
- Removed unused `BillingFixtures.createNewBillingProject`
- Removed `BillingFixtures.withBrandNewBillingProject` because it was only used in 1 Sam test and we no longer want to use
  v1 Create Billing Project APIs to get Google Projects due to Project per Workspace (PPW).  We will change that Sam test as well. 

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

### CODE REVIEW

**Review by ehigham — APPROVED** [review]

**Comment by andy7i** [comment]
the ticket # in the description does not match the PR https://broadworkbench.atlassian.net/browse/CA-1759

**Comment by andy7i** [comment]
I've realized this is probably for https://broadworkbench.atlassian.net/browse/QA-1759. Taking another look at it now

**Review by andy7i — APPROVED** [review]
👍 👍 
I'm excited to see v1 billing projects go 👋 

please update the ticket #

**Comment by Qi77Qi** [comment]
do we know if the the removed function is used by any services?

**Comment by gpolumbo-broad** [comment]
@Qi77Qi I grepped my entire `projects` directory that has most service repos cloned in it.  I couldn't not find any usages other than the test that was giving us grief.  So I am reasonably confident that it is not used anywhere, but I cannot say positively that there isn't something I missed, but I did the best I could to check.

**Pull request merged**
