### PR TITLE
workbench-model lib including ErrorReport

### PR DESCRIPTION
**Pull request by helgridly**
Before you start:
- [x] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [x] Bump the version in `project/Settings.scala` `createVersion()`
- [x] Update `CHANGELOG.md` for those libraries
- [x] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [x] Get two thumbsworth of PR review
- [x] Verify all tests go green, including CI tests
- [x] Squash commits and **merge to develop**
- [x] Delete branch after merge

After merging, _even if you haven't bumped the version_: 
- [ ] Update `README.md` and the `CHANGELOG.md` for any libs you changed with the new dependency string. The git hash is the same short version you see in GitHub (i.e. seven characters). You can commit these changes straight to develop.

### CODE REVIEW

**Comment by rtitle** [comment]
This looks fine. However I feel like it'd be good to add an `ErrorReportSpec` which would verify the JSON serialization/deserialization works correctly. I know it's essentially copy-pasted code, but in this repo it's untested (and the `Coverage decreased (-29.6%) to 20.37%` is bothering me :)).

**Review by rtitle — CHANGES_REQUESTED** [review]
This looks fine. However I feel like it'd be good to add an `ErrorReportSpec` which would verify the JSON serialization/deserialization works correctly. I know it's essentially copy-pasted code, but in this repo it's untested (and the `Coverage decreased (-29.6%) to 20.37%` is bothering me :)).

**Comment by helgridly** [comment]
I was planning on hammering this repo until coverage is >50% in a separate PR if it's all the same to you :)

**Review by jmthibault79 — APPROVED** [review]
I had some thoughts about ErrorReport but that should be done separately: https://broadinstitute.atlassian.net/browse/GAWB-2376

**Comment by helgridly** [comment]
There you go @rtitle. Coverage is now at 50%. Along with https://github.com/broadinstitute/workbench-libs/pull/8 coverage should be much higher on this repo now :)

**Pull request merged**
